In [4]:
import pandas as pd
import numpy as np
import seaborn as sms
import matplotlib.pyplot as plt

In [5]:

c= pd.read_csv("customers.csv")

In [6]:
c.columns

Index(['CustomerID', 'FirstName', 'MiddleInitial', 'LastName', 'CityID',
       'Address'],
      dtype='str')

In [7]:
c.shape

(98759, 6)

In [8]:
c.dtypes

CustomerID       int64
FirstName          str
MiddleInitial      str
LastName           str
CityID           int64
Address            str
dtype: object

CREATE TABLE `Customer_Details` (
	`customer_id` INT NOT NULL AUTO_INCREMENT,
	`customer_name` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`email_id` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`password` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`customer_id`) USING BTREE,
	UNIQUE INDEX `email_id` (`email_id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=52
;

In [9]:
c.rename(columns={'CustomerID': 'customer_id'}, inplace=True)

In [10]:
c.dtypes

customer_id      int64
FirstName          str
MiddleInitial      str
LastName           str
CityID           int64
Address            str
dtype: object

In [13]:
c.rename(columns={'FirstName'+'MiddleInitial'+'LastName' : 'customer_name'}, inplace=True)

In [15]:
c.head()

,customer_id,FirstName,MiddleInitial,LastName,CityID,Address
0,1,Stefanie,Y,Frye,79,97 Oak Avenue
1,2,Sandy,T,Kirby,96,52 White First Freeway
2,3,Lee,T,Zhang,55,921 White Fabien Avenue
3,4,Regina,S,Avery,40,75 Old Avenue
4,5,Daniel,S,Mccann,2,283 South Green Hague Avenue

In [16]:

c['customer_name'] = (
    c['FirstName'].str.strip() + ' ' +
    c['MiddleInitial'].str.strip() + ' ' +
    c['LastName'].str.strip()
)

# 2. Create email_id
c['email_id'] = (
    c['FirstName'].str[:3].str.lower() +
    c['MiddleInitial'].str[:1].str.lower() +
    c['LastName'].str[-1:].str.lower() +
    c['customer_id'].astype(str) +
    '@gmail.com'
)

# 3. Create password by reversing email_id without @gmail.com
c['password'] = (
    c['email_id']
    .str.replace('@gmail.com', '', regex=False)
    .str[::-1]
)

In [17]:
c.columns

Index(['customer_id', 'FirstName', 'MiddleInitial', 'LastName', 'CityID',
       'Address', 'customer_name', 'email_id', 'password'],
      dtype='str')

In [19]:
c.head()

,customer_id,FirstName,MiddleInitial,LastName,CityID,Address,customer_name,email_id,password
0,1,Stefanie,Y,Frye,79,97 Oak Avenue,Stefanie Y Frye,steye1@gmail.com,1eyets
1,2,Sandy,T,Kirby,96,52 White First Freeway,Sandy T Kirby,santy2@gmail.com,2ytnas
2,3,Lee,T,Zhang,55,921 White Fabien Avenue,Lee T Zhang,leetg3@gmail.com,3gteel
3,4,Regina,S,Avery,40,75 Old Avenue,Regina S Avery,regsy4@gmail.com,4ysger
4,5,Daniel,S,Mccann,2,283 South Green Hague Avenue,Daniel S Mccann,dansn5@gmail.com,5nsnad

In [23]:
c.to_csv("Customer.csv",header=True)

In [24]:
c.shape

(98759, 9)

In [22]:
c.rename(columns={'MiddleInitial': 'MiddleName'}, inplace=True)