In [1]:
import pandas as pd
import numpy as np
import seaborn as sms
import matplotlib.pyplot as plt

In [2]:

c= pd.read_csv("customers.csv")

In [3]:
c.columns

Index(['CustomerID', 'FirstName', 'MiddleInitial', 'LastName', 'CityID',
       'Address'],
      dtype='str')

In [4]:
c.shape

(98759, 6)

In [5]:
c.dtypes

CustomerID       int64
FirstName          str
MiddleInitial      str
LastName           str
CityID           int64
Address            str
dtype: object

CREATE TABLE `Customer_Details` (
	`customer_id` INT NOT NULL AUTO_INCREMENT,
	`customer_name` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`email_id` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`password` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`customer_id`) USING BTREE,
	UNIQUE INDEX `email_id` (`email_id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=52
;

In [6]:
c.rename(columns={'CustomerID': 'customer_id'}, inplace=True)

In [7]:
c.dtypes

customer_id      int64
FirstName          str
MiddleInitial      str
LastName           str
CityID           int64
Address            str
dtype: object

In [8]:
c.rename(columns={'FirstName'+'MiddleInitial'+'LastName' : 'customer_name'}, inplace=True)

In [9]:
c.head()

,customer_id,FirstName,MiddleInitial,LastName,CityID,Address
0,1,Stefanie,Y,Frye,79,97 Oak Avenue
1,2,Sandy,T,Kirby,96,52 White First Freeway
2,3,Lee,T,Zhang,55,921 White Fabien Avenue
3,4,Regina,S,Avery,40,75 Old Avenue
4,5,Daniel,S,Mccann,2,283 South Green Hague Avenue

In [10]:
c.fillna('',inplace=True)

,customer_id,FirstName,MiddleInitial,LastName,CityID,Address
0,1,Stefanie,Y,Frye,79,97 Oak Avenue
1,2,Sandy,T,Kirby,96,52 White First Freeway
2,3,Lee,T,Zhang,55,921 White Fabien Avenue
3,4,Regina,S,Avery,40,75 Old Avenue
4,5,Daniel,S,Mccann,2,283 South Green Hague Avenue
...,...,...,...,...,...,...
98754,98755,Yvette,C,Campos,27,945 Oak Parkway
98755,98756,Angelo,X,Mc Millan,82,99 Fabien Street
98756,98757,Shari,J,Prince,81,791 Milton Drive
98757,98758,Stuart,K,Cameron,57,149 Clarendon Road
98758,98759,Willie,E,Lawson,94,50 Fabien Freeway

In [11]:

c['customer_name'] = (
    c['FirstName'].str.strip() + ' ' +
    c['MiddleInitial'].str.strip() + ' ' +
    c['LastName'].str.strip()
)

# 2. Create email_id
c['email_id'] = (
    c['FirstName'].str[:3].str.lower() +
    c['LastName'].str[-1:].str.lower() +
    c['customer_id'].astype(str) +
    '@gmail.com'
)

# 3. Create password by reversing email_id without @gmail.com
c['password'] = (
    c['email_id']
    .str.replace('@gmail.com', '', regex=False)
    .str[::-1]
)

In [12]:
c.columns

Index(['customer_id', 'FirstName', 'MiddleInitial', 'LastName', 'CityID',
       'Address', 'customer_name', 'email_id', 'password'],
      dtype='str')

In [13]:
c.head()

,customer_id,FirstName,MiddleInitial,LastName,CityID,Address,customer_name,email_id,password
0,1,Stefanie,Y,Frye,79,97 Oak Avenue,Stefanie Y Frye,stee1@gmail.com,1eets
1,2,Sandy,T,Kirby,96,52 White First Freeway,Sandy T Kirby,sany2@gmail.com,2ynas
2,3,Lee,T,Zhang,55,921 White Fabien Avenue,Lee T Zhang,leeg3@gmail.com,3geel
3,4,Regina,S,Avery,40,75 Old Avenue,Regina S Avery,regy4@gmail.com,4yger
4,5,Daniel,S,Mccann,2,283 South Green Hague Avenue,Daniel S Mccann,dann5@gmail.com,5nnad

In [14]:
c.shape

(98759, 9)

In [15]:
c.rename(columns={'MiddleInitial': 'MiddleName'}, inplace=True)

In [16]:
c.to_csv("Customer.csv",header=True)

In [17]:
c.head()

,customer_id,FirstName,MiddleName,LastName,CityID,Address,customer_name,email_id,password
0,1,Stefanie,Y,Frye,79,97 Oak Avenue,Stefanie Y Frye,stee1@gmail.com,1eets
1,2,Sandy,T,Kirby,96,52 White First Freeway,Sandy T Kirby,sany2@gmail.com,2ynas
2,3,Lee,T,Zhang,55,921 White Fabien Avenue,Lee T Zhang,leeg3@gmail.com,3geel
3,4,Regina,S,Avery,40,75 Old Avenue,Regina S Avery,regy4@gmail.com,4yger
4,5,Daniel,S,Mccann,2,283 South Green Hague Avenue,Daniel S Mccann,dann5@gmail.com,5nnad

In [18]:
c.CityID.nunique()

96

In [19]:
c.shape

(98759, 9)

In [20]:
c.drop(['CityID'],inplace=True,axis=1)

In [21]:
c.to_csv("Customer.csv",header=True)

In [22]:
c.isnull().sum()

customer_id      0
FirstName        0
MiddleName       0
LastName         0
Address          0
customer_name    0
email_id         0
password         0
dtype: int64