In [1]:
import pandas as pd
import numpy as np
import seaborn as sms
import matplotlib.pyplot as plt

In [2]:
ls

 Volume in drive C is Windows
 Volume Serial Number is AC60-AD3D

 Directory of C:\Users\Lakshmi Priya\OneDrive\Documents\GitHub\Organic-food-tracebality

13-08-2026  23:14    <DIR>          .
27-07-2026  22:30    <DIR>          ..
11-08-2026  23:24    <DIR>          .ipynb_checkpoints
27-07-2026  23:29                 5 .python-version
28-07-2026  22:37    <DIR>          .venv
06-08-2026  22:39    <DIR>          __pycache__
06-08-2026  22:36             7,335 app.py
06-08-2026  20:48    <DIR>          assets
03-08-2026  21:45            13,176 cart_page.py
07-08-2026  23:33               156 categories.csv
07-08-2026  23:35            11,893 categories.ipynb
02-08-2026  21:43             2,964 categories.py
06-08-2026  22:36             2,526 category_page.py
06-08-2026  22:36    <DIR>          components
06-08-2026  22:36             1,059 config.py
12-08-2026  23:18         9,774,936 Customer.csv
12-08-2026  23:27            19,917 Customer.ipynb
07-08-2026  23:41         4,436,738 customers.csv
06-08-2026  22:36            26,339 db_manager.py
06-08-2026  22:36             2,597 favourites.py
01-08-2026  23:05             1,461 init_db.py
06-08-2026  22:36            11,297 login_page.py
27-07-2026  23:29               102 main.py
31-07-2026  21:16            24,576 organic_food.db
29-07-2026  23:07    <DIR>          pages
31-07-2026  23:01    <DIR>          product_icons
13-08-2026  22:59            40,915 products.csv
13-08-2026  23:14            27,657 Products.ipynb
06-08-2026  22:36            20,659 products.py
28-07-2026  22:36               237 pyproject.toml
27-07-2026  22:30                54 README.md
31-07-2026  22:14                59 requirements.txt
11-08-2026  23:02       517,020,842 sales.csv
13-08-2026  23:06            89,589 Sales.ipynb
13-08-2026  22:57        73,201,827 sales_date.csv
27-07-2026  23:36                23 sample.txt
06-08-2026  22:36             4,702 schema.sql
03-08-2026  21:46             5,947 traceability_page.py
30-07-2026  22:45    <DIR>          utils
28-07-2026  22:36           115,081 uv.lock
03-08-2026  21:45             2,772 wishlist_page.py
              31 File(s)    604,867,441 bytes
              10 Dir(s)  100,931,837,952 bytes free

In [3]:

Products= pd.read_csv("Products.csv")

In [4]:
Products.head()

,product_id,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,3,Flour - Whole Wheat,74.2988,2018-02-16 08:21:49.190,2018-03-18 08:21:49.190,47,7
1,2,3,Cookie Chocolate Chip With,91.2329,2017-02-12 11:39:10.970,2017-03-14 11:39:10.970,74,29
2,3,9,Onions - Cippolini,9.1379,2018-03-15 08:11:51.560,2018-04-14 08:11:51.560,33,22
3,4,9,"Sauce - Gravy, Au Jus, Mix",54.3055,2017-07-16 00:46:28.880,2017-08-15 00:46:28.880,93,30
4,5,2,Artichokes - Jerusalem,65.4771,2017-08-16 14:13:35.430,2017-09-15 14:13:35.430,37,25

In [5]:
Products.columns

Index(['product_id', 'category_id', 'product_name', 'price',
       'manufacture_date', 'expiry_date', 'quantity', 'discount'],
      dtype='str')

CREATE TABLE `Product` (
	`product_id` INT NOT NULL AUTO_INCREMENT,
	`category_id` INT NULL DEFAULT NULL,
	`product_name` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`price` DECIMAL(10,2) NULL DEFAULT NULL,
	`manufacture_date` DATE NULL DEFAULT NULL,
	`expiry_date` DATE NULL DEFAULT NULL,
	`quantity` INT NULL DEFAULT NULL,
	`discount` DECIMAL(5,2) NULL DEFAULT NULL,
	`onboarding_date` DATE NULL DEFAULT NULL,
	`manufacturer_name` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`unit` VARCHAR(50) NULL DEFAULT 'kg' COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`product_id`) USING BTREE,
	INDEX `category_id` (`category_id`) USING BTREE,
	CONSTRAINT `Product_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `Category` (`category_id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=103
;

In [6]:
Products.rename(columns={'CategoryID': 'category_id'}, inplace=True)

In [7]:
Products.rename(columns={'ProductName': 'product_name','Price': 'price','ModifyDate': 'manufacture_date'}, inplace=True)

In [8]:
Products.head()

,product_id,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,3,Flour - Whole Wheat,74.2988,2018-02-16 08:21:49.190,2018-03-18 08:21:49.190,47,7
1,2,3,Cookie Chocolate Chip With,91.2329,2017-02-12 11:39:10.970,2017-03-14 11:39:10.970,74,29
2,3,9,Onions - Cippolini,9.1379,2018-03-15 08:11:51.560,2018-04-14 08:11:51.560,33,22
3,4,9,"Sauce - Gravy, Au Jus, Mix",54.3055,2017-07-16 00:46:28.880,2017-08-15 00:46:28.880,93,30
4,5,2,Artichokes - Jerusalem,65.4771,2017-08-16 14:13:35.430,2017-09-15 14:13:35.430,37,25

In [9]:
Products.rename(columns={'ProductID': 'product_id'}, inplace=True)

In [10]:
Products.head()

,product_id,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,3,Flour - Whole Wheat,74.2988,2018-02-16 08:21:49.190,2018-03-18 08:21:49.190,47,7
1,2,3,Cookie Chocolate Chip With,91.2329,2017-02-12 11:39:10.970,2017-03-14 11:39:10.970,74,29
2,3,9,Onions - Cippolini,9.1379,2018-03-15 08:11:51.560,2018-04-14 08:11:51.560,33,22
3,4,9,"Sauce - Gravy, Au Jus, Mix",54.3055,2017-07-16 00:46:28.880,2017-08-15 00:46:28.880,93,30
4,5,2,Artichokes - Jerusalem,65.4771,2017-08-16 14:13:35.430,2017-09-15 14:13:35.430,37,25

In [11]:
Products.dtypes

product_id            int64
category_id           int64
product_name            str
price               float64
manufacture_date        str
expiry_date             str
quantity              int64
discount              int64
dtype: object

In [12]:

Products['manufacture_date'] = pd.to_datetime(Products['manufacture_date'])

# Create expiry_date = manufacture_date + 30 days
Products['expiry_date'] = Products['manufacture_date'] + pd.Timedelta(days=30)

# Random quantity between 20 and 100
Products['quantity'] = np.random.randint(20, 101, size=len(Products))

# Random discount between 5% and 30%
Products['discount'] = np.random.randint(5, 31, size=len(Products))

In [13]:
Products.columns

Index(['product_id', 'category_id', 'product_name', 'price',
       'manufacture_date', 'expiry_date', 'quantity', 'discount'],
      dtype='str')

In [14]:
Products=Products[['product_id','category_id', 'product_name', 'price', 'manufacture_date','expiry_date', 'quantity', 'discount']]

In [15]:
Products.head()

,product_id,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,3,Flour - Whole Wheat,74.2988,2018-02-16 08:21:49.190,2018-03-18 08:21:49.190,71,24
1,2,3,Cookie Chocolate Chip With,91.2329,2017-02-12 11:39:10.970,2017-03-14 11:39:10.970,28,14
2,3,9,Onions - Cippolini,9.1379,2018-03-15 08:11:51.560,2018-04-14 08:11:51.560,47,29
3,4,9,"Sauce - Gravy, Au Jus, Mix",54.3055,2017-07-16 00:46:28.880,2017-08-15 00:46:28.880,44,27
4,5,2,Artichokes - Jerusalem,65.4771,2017-08-16 14:13:35.430,2017-09-15 14:13:35.430,57,21

In [16]:
Products.shape

(452, 8)

In [17]:
Products.to_csv("Products.csv",index=False)

In [18]:
Products=Products[Products.category_id!=8]
Products.shape

(424, 8)

In [19]:
sales_products=[413, 370, 134, 364, 185, 377, 308, 147, 442, 324, 369,  91, 344,
       419, 246, 439, 407, 137,  39,  62, 161, 356,  57, 103, 429,  67,
       408,  59, 152, 365,  94, 290, 233, 418, 311, 253,  95, 376, 197,
       270, 110, 273, 231,  32, 259, 422, 159,  55, 148, 332, 359, 416,
         8, 331, 267, 144,  12, 104, 209, 184, 266, 358, 216, 226,  60,
       199,  90, 235, 298, 191, 112, 153, 421, 297, 279, 187, 249, 424,
        47, 280, 139,  16, 281, 120, 319, 306, 345,   7, 105, 432, 179,
        36,  73, 396, 327, 192, 409, 316, 115, 425]

In [21]:
filtered_products = Products[Products['product_id'].isin(sales_products)]

In [22]:
filtered_products.shape

(100, 8)

In [23]:
filtered_products.to_csv("sales_products.csv",index=False)