In [4]:
import pandas as pd
import numpy as np
import seaborn as sms
import matplotlib.pyplot as plt

In [5]:
ls

 Volume in drive C is Windows
 Volume Serial Number is AC60-AD3D

 Directory of C:\Users\Lakshmi Priya\OneDrive\Documents\GitHub\Organic-food-tracebality

07-08-2026  22:44    <DIR>          .
27-07-2026  22:30    <DIR>          ..
07-08-2026  22:43    <DIR>          .ipynb_checkpoints
27-07-2026  23:29                 5 .python-version
28-07-2026  22:37    <DIR>          .venv
06-08-2026  22:39    <DIR>          __pycache__
06-08-2026  22:36             7,335 app.py
06-08-2026  20:48    <DIR>          assets
03-08-2026  21:45            13,176 cart_page.py
06-08-2026  22:41            12,294 categories.ipynb
02-08-2026  21:43             2,964 categories.py
06-08-2026  22:36             2,526 category_page.py
06-08-2026  22:36    <DIR>          components
06-08-2026  22:36             1,059 config.py
06-08-2026  22:36            26,339 db_manager.py
06-08-2026  22:36             2,597 favourites.py
01-08-2026  23:05             1,461 init_db.py
06-08-2026  22:36            11,297 login_page.py
27-07-2026  23:29               102 main.py
31-07-2026  21:16            24,576 organic_food.db
29-07-2026  23:07    <DIR>          pages
31-07-2026  23:01    <DIR>          product_icons
07-08-2026  22:44            36,846 products.csv
06-08-2026  22:41             9,466 Products.ipynb
06-08-2026  22:36            20,659 products.py
28-07-2026  22:36               237 pyproject.toml
27-07-2026  22:30                54 README.md
31-07-2026  22:14                59 requirements.txt
27-07-2026  23:36                23 sample.txt
06-08-2026  22:36             4,702 schema.sql
03-08-2026  21:46             5,947 traceability_page.py
30-07-2026  22:45    <DIR>          utils
28-07-2026  22:36           115,081 uv.lock
03-08-2026  21:45             2,772 wishlist_page.py
              24 File(s)        301,577 bytes
              10 Dir(s)  131,409,973,248 bytes free

In [6]:

Products= pd.read_csv("Products.csv")

In [7]:
Products.head()

,ProductID,ProductName,Price,CategoryID,Class,ModifyDate,Resistant,IsAllergic,VitalityDays
0,1,Flour - Whole Wheat,74.2988,3,Medium,2018-02-16 08:21:49.190,Durable,Unknown,0.0
1,2,Cookie Chocolate Chip With,91.2329,3,Medium,2017-02-12 11:39:10.970,Unknown,Unknown,0.0
2,3,Onions - Cippolini,9.1379,9,Medium,2018-03-15 08:11:51.560,Weak,False,111.0
3,4,"Sauce - Gravy, Au Jus, Mix",54.3055,9,Medium,2017-07-16 00:46:28.880,Durable,Unknown,0.0
4,5,Artichokes - Jerusalem,65.4771,2,Low,2017-08-16 14:13:35.430,Durable,True,27.0

In [8]:
Products.columns

Index(['ProductID', 'ProductName', 'Price', 'CategoryID', 'Class',
       'ModifyDate', 'Resistant', 'IsAllergic', 'VitalityDays'],
      dtype='str')

CREATE TABLE `Product` (
	`product_id` INT NOT NULL AUTO_INCREMENT,
	`category_id` INT NULL DEFAULT NULL,
	`product_name` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`price` DECIMAL(10,2) NULL DEFAULT NULL,
	`manufacture_date` DATE NULL DEFAULT NULL,
	`expiry_date` DATE NULL DEFAULT NULL,
	`quantity` INT NULL DEFAULT NULL,
	`discount` DECIMAL(5,2) NULL DEFAULT NULL,
	`onboarding_date` DATE NULL DEFAULT NULL,
	`manufacturer_name` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`unit` VARCHAR(50) NULL DEFAULT 'kg' COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`product_id`) USING BTREE,
	INDEX `category_id` (`category_id`) USING BTREE,
	CONSTRAINT `Product_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `Category` (`category_id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=103
;

In [9]:
Products.rename(columns={'CategoryID': 'category_id'}, inplace=True)

In [12]:
Products.rename(columns={'ProductName': 'product_name','Price': 'price','ModifyDate': 'manufacture_date'}, inplace=True)

In [13]:
Products.head()

,ProductID,product_name,price,category_id,Class,manufacture_date,Resistant,IsAllergic,VitalityDays
0,1,Flour - Whole Wheat,74.2988,3,Medium,2018-02-16 08:21:49.190,Durable,Unknown,0.0
1,2,Cookie Chocolate Chip With,91.2329,3,Medium,2017-02-12 11:39:10.970,Unknown,Unknown,0.0
2,3,Onions - Cippolini,9.1379,9,Medium,2018-03-15 08:11:51.560,Weak,False,111.0
3,4,"Sauce - Gravy, Au Jus, Mix",54.3055,9,Medium,2017-07-16 00:46:28.880,Durable,Unknown,0.0
4,5,Artichokes - Jerusalem,65.4771,2,Low,2017-08-16 14:13:35.430,Durable,True,27.0

In [14]:
Products.rename(columns={'ProductID': 'product_id'}, inplace=True)

In [15]:
Products.head()

,product_id,product_name,price,category_id,Class,manufacture_date,Resistant,IsAllergic,VitalityDays
0,1,Flour - Whole Wheat,74.2988,3,Medium,2018-02-16 08:21:49.190,Durable,Unknown,0.0
1,2,Cookie Chocolate Chip With,91.2329,3,Medium,2017-02-12 11:39:10.970,Unknown,Unknown,0.0
2,3,Onions - Cippolini,9.1379,9,Medium,2018-03-15 08:11:51.560,Weak,False,111.0
3,4,"Sauce - Gravy, Au Jus, Mix",54.3055,9,Medium,2017-07-16 00:46:28.880,Durable,Unknown,0.0
4,5,Artichokes - Jerusalem,65.4771,2,Low,2017-08-16 14:13:35.430,Durable,True,27.0

In [17]:
Products.dtypes

product_id            int64
product_name            str
price               float64
category_id           int64
Class                   str
manufacture_date        str
Resistant               str
IsAllergic              str
VitalityDays        float64
dtype: object

In [19]:

Products['manufacture_date'] = pd.to_datetime(Products['manufacture_date'])

# Create expiry_date = manufacture_date + 30 days
Products['expiry_date'] = Products['manufacture_date'] + pd.Timedelta(days=30)

# Random quantity between 20 and 100
Products['quantity'] = np.random.randint(20, 101, size=len(Products))

# Random discount between 5% and 30%
Products['discount'] = np.random.randint(5, 31, size=len(Products))

In [20]:
Products.columns

Index(['product_id', 'product_name', 'price', 'category_id', 'Class',
       'manufacture_date', 'Resistant', 'IsAllergic', 'VitalityDays',
       'expiry_date', 'quantity', 'discount'],
      dtype='str')

In [22]:
Products=Products[['product_id','category_id', 'product_name', 'price', 'manufacture_date','expiry_date', 'quantity', 'discount']]

In [23]:
Products.head()

,product_id,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,3,Flour - Whole Wheat,74.2988,2018-02-16 08:21:49.190,2018-03-18 08:21:49.190,40,28
1,2,3,Cookie Chocolate Chip With,91.2329,2017-02-12 11:39:10.970,2017-03-14 11:39:10.970,90,20
2,3,9,Onions - Cippolini,9.1379,2018-03-15 08:11:51.560,2018-04-14 08:11:51.560,77,19
3,4,9,"Sauce - Gravy, Au Jus, Mix",54.3055,2017-07-16 00:46:28.880,2017-08-15 00:46:28.880,60,7
4,5,2,Artichokes - Jerusalem,65.4771,2017-08-16 14:13:35.430,2017-09-15 14:13:35.430,75,24

In [25]:
Products.shape

(452, 8)

In [26]:
Products.to_csv("Products.csv",header=True)