In [1]:
import pandas as pd
import numpy as np
import seaborn as sms
import matplotlib.pyplot as plt

In [2]:
s= pd.read_csv("Sales.csv")

In [3]:
s.head()

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0
3,4,8,73966,176,19,0.2,0.0,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE
4,5,10,32653,310,9,0.0,0.0,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3

In [4]:
p=pd.read_csv("Products.csv")

In [5]:
p.head()

,product_id,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,3,Flour - Whole Wheat,74.2988,2018-02-16 08:21:49.190,2018-03-18 08:21:49.190,71,24
1,2,3,Cookie Chocolate Chip With,91.2329,2017-02-12 11:39:10.970,2017-03-14 11:39:10.970,28,14
2,3,9,Onions - Cippolini,9.1379,2018-03-15 08:11:51.560,2018-04-14 08:11:51.560,47,29
3,4,9,"Sauce - Gravy, Au Jus, Mix",54.3055,2017-07-16 00:46:28.880,2017-08-15 00:46:28.880,44,27
4,5,2,Artichokes - Jerusalem,65.4771,2017-08-16 14:13:35.430,2017-09-15 14:13:35.430,57,21

In [6]:
s.rename(columns={'ProductID': 'product_id'}, inplace=True)

In [7]:
df=pd.merge(s,p,on="product_id")

In [8]:
df.head()

,SalesID,SalesPersonID,CustomerID,product_id,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber,category_id,product_name,price,manufacture_date,expiry_date,quantity,discount
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,Vaccum Bag 10x13,44.2337,2018-01-06 22:26:53.580,2018-02-05 22:26:53.580,36,23
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,Sardines,62.5460,2017-12-03 21:41:12.420,2018-01-02 21:41:12.420,57,14
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,Crab - Imitation Flakes,79.0184,2017-08-19 07:18:29.890,2017-09-18 07:18:29.890,51,16
3,4,8,73966,176,19,0.2,0.0,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,Smirnoff Green Apple Twist,81.3167,2017-08-27 17:08:59.840,2017-09-26 17:08:59.840,44,11
4,5,10,32653,310,9,0.0,0.0,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,Coffee - Dark Roast,79.9780,2018-01-14 19:33:15.530,2018-02-13 19:33:15.530,76,14

In [9]:
df.drop(['SalesPersonID','manufacture_date','expiry_date','quantity','Discount','TotalPrice','product_name'],inplace=True,axis=1)

In [10]:
df.head()

,SalesID,CustomerID,product_id,Quantity,SalesDate,TransactionNumber,category_id,price,discount
0,1,27039,381,7,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,44.2337,23
1,2,25011,61,7,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,62.5460,14
2,3,94024,23,24,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,79.0184,16
3,4,73966,176,19,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,81.3167,11
4,5,32653,310,9,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,79.9780,14

In [11]:
df.rename(columns={'CustomerID': 'customer_id'}, inplace=True)

In [12]:
df['price_after_discount'] = df['price'] - (df['price'] * df['discount'] / 100)

In [13]:
df['price_after_discount'] = (
    df['price'] - (df['price'] * df['discount'] / 100)
).round(2)

In [14]:
df.head()

,SalesID,customer_id,product_id,Quantity,SalesDate,TransactionNumber,category_id,price,discount,price_after_discount
0,1,27039,381,7,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,44.2337,23,34.06
1,2,25011,61,7,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,62.5460,14,53.79
2,3,94024,23,24,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,79.0184,16,66.38
3,4,73966,176,19,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,81.3167,11,72.37
4,5,32653,310,9,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,79.9780,14,68.78

In [15]:
df.rename(columns={'SalesID': 'order_id'}, inplace=True)

In [16]:
df.head()

,order_id,customer_id,product_id,Quantity,SalesDate,TransactionNumber,category_id,price,discount,price_after_discount
0,1,27039,381,7,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,44.2337,23,34.06
1,2,25011,61,7,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,62.5460,14,53.79
2,3,94024,23,24,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,79.0184,16,66.38
3,4,73966,176,19,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,81.3167,11,72.37
4,5,32653,310,9,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,79.9780,14,68.78

In [17]:
df.rename(columns={'Quantity': 'product_count'}, inplace=True)

In [18]:
df.head()

,order_id,customer_id,product_id,product_count,SalesDate,TransactionNumber,category_id,price,discount,price_after_discount
0,1,27039,381,7,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,44.2337,23,34.06
1,2,25011,61,7,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,62.5460,14,53.79
2,3,94024,23,24,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,79.0184,16,66.38
3,4,73966,176,19,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,81.3167,11,72.37
4,5,32653,310,9,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,79.9780,14,68.78

In [19]:
df.rename(columns={'price': 'product_price','discount':'product_discount'}, inplace=True)

In [20]:
df.head()

,order_id,customer_id,product_id,product_count,SalesDate,TransactionNumber,category_id,product_price,product_discount,price_after_discount
0,1,27039,381,7,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,44.2337,23,34.06
1,2,25011,61,7,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,62.5460,14,53.79
2,3,94024,23,24,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,79.0184,16,66.38
3,4,73966,176,19,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,81.3167,11,72.37
4,5,32653,310,9,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,79.9780,14,68.78

In [21]:
df['SalesDate'] = pd.to_datetime(df['SalesDate'])

df['order_date'] = df['SalesDate'].dt.date
df['order_time'] = df['SalesDate'].dt.time

In [22]:
# Convert SalesDate from string to datetime
df['SalesDate'] = pd.to_datetime(df['SalesDate'])

# Create separate date and time columns
df['order_date'] = df['SalesDate'].dt.date
df['order_time'] = df['SalesDate'].dt.time

In [23]:
df.dtypes

order_id                         int64
customer_id                      int64
product_id                       int64
product_count                    int64
SalesDate               datetime64[us]
TransactionNumber                  str
category_id                      int64
product_price                  float64
product_discount                 int64
price_after_discount           float64
order_date                      object
order_time                      object
dtype: object

In [24]:
df.head()

,order_id,customer_id,product_id,product_count,SalesDate,TransactionNumber,category_id,product_price,product_discount,price_after_discount,order_date,order_time
0,1,27039,381,7,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,1,44.2337,23,34.06,2018-02-05,07:38:25.430000
1,2,25011,61,7,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,8,62.5460,14,53.79,2018-02-02,16:03:31.150000
2,3,94024,23,24,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,11,79.0184,16,66.38,2018-05-03,19:31:56.880000
3,4,73966,176,19,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE,6,81.3167,11,72.37,2018-04-07,14:43:55.420000
4,5,32653,310,9,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3,9,79.9780,14,68.78,2018-02-12,15:37:03.940000

In [25]:
df.drop(['SalesDate','TransactionNumber'],inplace=True,axis=1)

#    data cleaning

In [26]:
df.head()

,order_id,customer_id,product_id,product_count,category_id,product_price,product_discount,price_after_discount,order_date,order_time
0,1,27039,381,7,1,44.2337,23,34.06,2018-02-05,07:38:25.430000
1,2,25011,61,7,8,62.5460,14,53.79,2018-02-02,16:03:31.150000
2,3,94024,23,24,11,79.0184,16,66.38,2018-05-03,19:31:56.880000
3,4,73966,176,19,6,81.3167,11,72.37,2018-04-07,14:43:55.420000
4,5,32653,310,9,9,79.9780,14,68.78,2018-02-12,15:37:03.940000

In [27]:
# Count how many times each product appears in each category
product_counts = (
    df.groupby(['category_id', 'product_id'])
      .size()
      .reset_index(name='count')
)
product_counts.head(20)

    category_id  product_id  count
0             1          15  14878
1             1          27  14894
2             1          42  14857
3             1          52  15002
4             1          62  15052
5             1          69  14876
6             1          83  15033
7             1          84  14977
8             1          92  14957
9             1          95  15231
10            1         105  15073
11            1         107  14893
12            1         108  14900
13            1         109  14721
14            1         139  15052
15            1         141  15019
16            1         143  14911
17            1         156  14762
18            1         170  14901
19            1         175  14931

In [28]:
#Get top 10 products for each category
top_10_products = (
    product_counts
    .sort_values(['category_id', 'count'], ascending=[True, False])
    .groupby('category_id')
    .head(10)
    .reset_index(drop=True)
)
top_10_products.head(20)

    category_id  product_id  count
0             1          95  15231
1             1         197  15117
2             1         216  15097
3             1         364  15092
4             1         279  15081
5             1         105  15073
6             1         290  15060
7             1          62  15052
8             1         139  15052
9             1         377  15048
10            2          60  15132
11            2         344  15075
12            2         327  15063
13            2         120  15025
14            2         134  15020
15            2          16  15014
16            2         267  15001
17            2         432  14991
18            2         281  14987
19            2         418  14981

In [29]:
df.shape

(6758125, 10)

In [30]:
df.columns

Index(['order_id', 'customer_id', 'product_id', 'product_count', 'category_id',
       'product_price', 'product_discount', 'price_after_discount',
       'order_date', 'order_time'],
      dtype='str')

In [31]:
df.product_id.nunique()

452

In [32]:
# 3. Get only the product IDs that are in the top 10 of their category
top_product = top_10_products[['category_id', 'product_id']]

# 4. Filter the ORIGINAL dataframe
df_top10 = df.merge(
    top_product,
    on=['category_id', 'product_id'],
    how='inner'
)

# 5. View the result
df_top10.shape

(1659870, 10)

In [33]:
df_top10.head()

,order_id,customer_id,product_id,product_count,category_id,product_price,product_discount,price_after_discount,order_date,order_time
0,2,25011,61,7,8,62.5460,14,53.79,2018-02-02,16:03:31.150000
1,6,28663,413,8,3,95.4065,5,90.64,2018-02-07,10:33:24.990000
2,7,46674,370,12,4,21.8806,10,19.69,2018-03-02,23:09:58.750000
3,15,19310,134,5,2,39.8545,6,37.46,2018-01-26,05:20:52.510000
4,16,91867,364,24,1,8.8429,28,6.37,2018-04-30,23:55:11.560000

In [34]:
df_top10.category_id.unique()

array([ 8,  3,  4,  2,  1,  6,  5, 10,  9, 11,  7])

In [35]:
# Convert order_date
df_top10["order_date"] = pd.to_datetime(
    df_top10["order_date"],
    errors="coerce"
)

In [36]:
df_top10 = df_top10[['order_id','customer_id', 'product_id', 'product_count', 'product_price','product_discount', 
                     'price_after_discount', 'order_date','category_id']]

In [37]:
df_top10.head()

,order_id,customer_id,product_id,product_count,product_price,product_discount,price_after_discount,order_date,category_id
0,2,25011,61,7,62.5460,14,53.79,2018-02-02,8
1,6,28663,413,8,95.4065,5,90.64,2018-02-07,3
2,7,46674,370,12,21.8806,10,19.69,2018-03-02,4
3,15,19310,134,5,39.8545,6,37.46,2018-01-26,2
4,16,91867,364,24,8.8429,28,6.37,2018-04-30,1

In [38]:
category_orders = df_top10.groupby("category_id").size().sort_values()

category_orders

category_id
8     150035
2     150289
3     150740
6     150749
11    150831
1     150903
10    151035
4     151121
5     151302
7     151363
9     151502
dtype: int64

In [39]:
df_top10.shape

(1659870, 9)

In [40]:
sales_date=df_top10[df_top10.category_id!=8]
sales_date.shape

(1509835, 9)

In [41]:
sales_date.head()

,order_id,customer_id,product_id,product_count,product_price,product_discount,price_after_discount,order_date,category_id
1,6,28663,413,8,95.4065,5,90.64,2018-02-07,3
2,7,46674,370,12,21.8806,10,19.69,2018-03-02,4
3,15,19310,134,5,39.8545,6,37.46,2018-01-26,2
4,16,91867,364,24,8.8429,28,6.37,2018-04-30,1
5,17,14612,185,4,48.4195,19,39.22,2018-01-20,6

In [42]:
sales_date.drop(['category_id'],inplace=True,axis=1)

In [43]:
sales_date.head()

,order_id,customer_id,product_id,product_count,product_price,product_discount,price_after_discount,order_date
1,6,28663,413,8,95.4065,5,90.64,2018-02-07
2,7,46674,370,12,21.8806,10,19.69,2018-03-02
3,15,19310,134,5,39.8545,6,37.46,2018-01-26
4,16,91867,364,24,8.8429,28,6.37,2018-04-30
5,17,14612,185,4,48.4195,19,39.22,2018-01-20

In [44]:

sales_date.dtypes

order_id                        int64
customer_id                     int64
product_id                      int64
product_count                   int64
product_price                 float64
product_discount                int64
price_after_discount          float64
order_date              datetime64[s]
dtype: object

In [45]:
sales_date.to_csv("sales_date.csv",index=False)

In [46]:
sales_date.product_id.nunique()

100

In [47]:
sales_date.product_id.unique()

array([413, 370, 134, 364, 185, 377, 308, 147, 442, 324, 369,  91, 344,
       419, 246, 439, 407, 137,  39,  62, 161, 356,  57, 103, 429,  67,
       408,  59, 152, 365,  94, 290, 233, 418, 311, 253,  95, 376, 197,
       270, 110, 273, 231,  32, 259, 422, 159,  55, 148, 332, 359, 416,
         8, 331, 267, 144,  12, 104, 209, 184, 266, 358, 216, 226,  60,
       199,  90, 235, 298, 191, 112, 153, 421, 297, 279, 187, 249, 424,
        47, 280, 139,  16, 281, 120, 319, 306, 345,   7, 105, 432, 179,
        36,  73, 396, 327, 192, 409, 316, 115, 425])

In [48]:
sales_date["order_date"] = pd.to_datetime(sales_date["order_date"])

min_date = sales_date["order_date"].min()
max_date = sales_date["order_date"].max()

print("Minimum date:", min_date)
print("Maximum date:", max_date)

Minimum date: 2018-01-01 00:00:00
Maximum date: 2018-05-09 00:00:00

In [49]:
sales_date["order_date"] = sales_date["order_date"].apply(
    lambda x: x.replace(year=2026)
)

In [50]:
sales_date["order_date"] = pd.to_datetime(sales_date["order_date"])

min_date = sales_date["order_date"].min()
max_date = sales_date["order_date"].max()

print("Minimum date:", min_date)
print("Maximum date:", max_date)

Minimum date: 2026-01-01 00:00:00
Maximum date: 2026-05-09 00:00:00

In [51]:
sales_date.to_csv("sales_date.csv",index=False)

In [53]:
sales_date.isnull().sum()

order_id                    0
customer_id                 0
product_id                  0
product_count               0
product_price               0
product_discount            0
price_after_discount        0
order_date              15029
dtype: int64